version: '3'
services:
  srl:
    image: grashoper20/srl:local
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - srl
    volumes:
      - ./:/var/www/html/:rw
      - $SICKBEARDLOCATION:/var/www/sickrage/:ro
  npm-watch:
    image: node:8-alpine
    networks:
      - srl
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html/:rw
    working_dir: /var/www/html/
    entrypoint:
      - /bin/sh
      - -c
      - |
        yarn install
        npm run watch

#        NODE_ENV=development node node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js --host=0.0.0.0

networks:
  srl:
volumes:
  laravel-storage:
